### ISSUE TITLE
User Story: Setup VScode. Epic#1

### ISSUE THREAD

**Issue by raed-nimer** [raed-nimer/CI-django-tech-blog#2]
**Acceptance Criteria**
- Connect VScode with the project
- Create Virtual environment and install necessary packages for this project

 **Tasks**

- [x] Task 1 - clone repository from github to VScode
- [x] Task 2 - create virtual environment and add packages
- [x] Task 3 - Install django 

Epic[#1](https://github.com/raed-nimer/CI-django-tech-blog/issues/1)
